/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#faf8ff",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#eaedff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "on-surface": "#131b2e",
        "on-surface-variant": "#464554",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        outline: "#767586",
        "outline-variant": "#c7c4d7",
        "surface-tint": "#494bd6",
        primary: "#4648d4",
        "on-primary": "#ffffff",
        "primary-container": "#6063ee",
        "on-primary-container": "#fffbff",
        "inverse-primary": "#c0c1ff",
        secondary: "#4e45d5",
        "on-secondary": "#ffffff",
        "secondary-container": "#6860ef",
        "on-secondary-container": "#fffbff",
        tertiary: "#4651b9",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#606ad4",
        "on-tertiary-container": "#fffbff",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#faf8ff",
        "on-background": "#131b2e",
        "surface-variant": "#dae2fd",
        "surface-light": "#ffffff",
        "surface-dark": "#020617",
        "chat-user-bubble": "#f1f5f9",
        "chat-ai-bubble": "#ffffff",
        "border-subtle": "#e2e8f0",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "sidebar-width": "280px",
        "content-max-width": "800px",
        gutter: "1.5rem",
        "stack-gap": "2rem",
      },
      fontFamily: {
        sans: ["Inter", "Noto Sans Arabic", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
